#!/bin/sh
# /etc/init.d/gatekeeper
# gatekeeper	initscript for the gatekeeper package
#		Copr. 2016 by Vaasa Hacklab <info@vaasa.hacklab.fi>
### BEGIN INIT INFO
# Provides:          gatekeeper
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gatekeeper door opener
# Description:       Respond to calls and open the door accordingly
### END INIT INFO

DIR=/home/ovi/gatekeeper
DAEMON=$DIR/gatekeeper.py
DAEMON_NAME=gatekeeper
DAEMON_USER=root
DAEMON_GROUP=root
DAEMON_OPTS=""
PIDFILE=/var/run/gatekeeper.pid

test -f ${DAEMON} || exit 0

. /lib/lsb/init-functions

# [ -r /etc/default/rng-tools ] && . /etc/default/rng-tools


do_start () {
	log_daemon_msg "Starting system $DAEMON_NAME daemon"
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --startas $DAEMON --chuid $DAEMON_USER -- $DAEMON_OPTS
	log_end_msg $?
}
do_stop () {
	log_daemon_msg "Stopping system $DAEMON_NAME daemon"
	start-stop-daemon --stop --pidfile $PIDFILE --retry 10
	log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
